import "./globals.css";
import Header from "../components/Header";
import { ThemeProvider } from "../context/ThemeContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased
         bg-white dark:bg-slate-800 text-black dark:text-gray-100 min-h-screen transition-all duration-300`}>
        <ThemeProvider>
          {/* Header */}
          <Header />
          <main className="">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
